kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
  - role: control-plane
    extraPortMappings:
      - containerPort: 80   # Porta HTTP dentro do cluster
        hostPort: 8080      # Porta exposta no host
        protocol: TCP
      - containerPort: 443  # Porta HTTPS dentro do cluster
        hostPort: 8443      # Porta exposta no host
        protocol: TCP
  - role: worker
  - role: worker
